### ISSUE TITLE
Web Application - Creating Pyramid project with Chameleon templates

### ISSUE THREAD

**Issue by tony-ruchti** [talkpython/mastering-pycharm-course#26]
This isn't necessarily a mistake in your book, but PyCharm currently has a bug that isn't getting a lot of attention. the bug prevents anyone from following through the chapter as written. JetBrains is aware of it, here's the following post I found regarding it that provides a link to their YouTrack page of the bug https://intellij-support.jetbrains.com/hc/en-us/community/posts/360005076019-PyCharm-Pyramid-Project-with-Chameleon-Templates-Selected

Hopefully you can provide a work around for the time being?

**Comment by mikeckennedy** [comment]
Hi @hdtroll thanks for the heads up on this. 

What a hassle. It used to work (clearly as you saw in the video!). But stopped working. I gave them a push to try to fix it in the comments:

https://youtrack.jetbrains.com/issue/PY-37708#focus=streamItem-27-3754003.0-0

I don't really want to change the book or video because it used to work this way, and will soon in the future I'm sure. If they don't respond soon, I'll reach out to my contacts there.

**Comment by spgraham** [comment]
Hey @mikeckennedy 
Just been following the course as well (nothing to so at Christmas - what can you do).
The issue still not fixed with Chameleon, which is a shame because the rest of your course is excellent and JB letting the side down in Pycharm Pro, and you shouldn't need to change the course since they have a bug.
Checked the Jetbrains issue and says it's not on a fix version list yet.
Could you give them a nudge :-)
All the best
Steve

**Comment by mikeckennedy** [comment]
Thanks guys. I posted another, more info filled comment on YouTrack and reach out to some folks at JetBrains.

**Comment by mikeckennedy** [comment]
Good news! PyCharm/JetBrains finally adopted directly invoking cookiecutter so I think this is now fixed.

https://youtrack.jetbrains.com/issue/PY-37708#focus=Comments-27-4002359.0-0


**Aleksei Kniazev**
> We now use cookiecutter to create new Pyramid projects, so this is no longer an issue, closing it. See PY-22311 for details.
