### ISSUE TITLE
Python ModuleNotFoundError

### ISSUE THREAD

**Issue by xchapman** [talkpython/mastering-pycharm-course#58]
I have been struggling with the **ModuleNotFoundError: No module named 'requests'** error for a while now. I am running Python 3.8 on a Windows 10 platform. I downloaded the **python-jumpstart-course-demos** files using the **GitHub Desktop app**. This error is affecting everything I am attempting to do with Python in PyCharm. I believe that it may be a path issue. Usually when I import a library this error appears. 

<img width="840" alt="path_error_01" src="https://user-images.githubusercontent.com/53450486/149680024-0f826ee9-bb19-42de-b0c5-88479fe9f703.png">

**Comment by mikeckennedy** [comment]
Hi @xchapman The problem is you're running your system-wide Python (`c:\users\jbc\appdata\local\programs\python38\python.exe`) and requests is not install. You should create a virtual environment, activate it, then install requests into it. You can do this via PyCharm. See the bottom right in Python section in the bottom right of PyCharm.
